namespace TeamDEV.Asl.PInvoke {
    public enum FacilityCode : ushort {
        Debugger = 0x01,
        RpcRuntime = 0x02,
        RpcStubs = 0x03,
        IOErrorCode = 0x04,
        NTWin32 = 0x07,
        NTCert = 0x08,
        NTSSPI = 0x09,
        MUIErrorCode = 0x0B,
        TerminalServer = 0x0A,
        UsbErrorCode = 0x10,
        HIDErrorCode = 0x11,
        FirewireErrorCode = 0x12,
        ClusterErrorCode = 0x13,
        ACPIErrorCode = 0x14,
        SXSErrorCode = 0x15,
        Transaction = 0x19,
        CommonLog = 0x1A,
        Video = 0x1B,
        FilterManager = 0x1C,
        Monitor = 0x1D,
        GraphicsKernel = 0x1E,
        DriverFramework = 0x20,
        FVEErrorCode = 0x21,
        FWPErrorCode = 0x22,
        NDISErrorCode = 0x23,
        Hypervisor = 0x35,
        Virtualization = 0x37,
        VolumeManager = 0x38,
        BCDErrorCode = 0x39,
        DIS = 0x3C,
        Win32K_NTUser = 0x3E,
        Win32K_NTGdi = 0x3F,
        IPSEC = 0x36,
    }
}